name: fullstack-app

description: Deploy a serverless fullstack application using Express.js and React on AWS Lambda and AWS HTTP API
keywords: serverless, express, react, fullstack, aws, aws lambda
repo: https://github.com/serverless-components/fullstack-app
license: MIT
service: fullstack-app

provider:
  name: aws